#!/bin/bash
pushd $(dirname `which "$0"`) >/dev/null; fieldhome="$PWD"; popd >/dev/null

out=$fieldhome/out/production
java=/usr/lib/jvm/java-9-jdk/bin/java


#(echo '$fieldhome/f_server $java)' | at now)&

LD_LIBRARY_PATH=$out/fieldcore/linux64 \
$java \
    -DappDir=$fieldhome \
    -Xmx4g \
    -Xms4g \
    --add-exports jdk.management/com.sun.management.internal=ALL-UNNAMED \
    -cp \
$fieldhome/lib/linux64:\
$fieldhome/out/artifacts/fieldlinker_jar/fieldlinker.jar:\
/usr/lib/jvm/java-8-openjdk/lib/tools.jar:\
$fieldhome/lib/*:\
$fieldhome/out/artifacts/fieldagent_jar/fieldagent.jar:\
$out/fieldlinker/*:\
$out/fieldlinker/orientdb/*:\
$out/fieldlinker/guava-16.0.1.jar:\
$out/fieldlinker:\
$out/fieldcef_macosx \
    -Djava.library.path=\
$fieldhome:\
$out/fieldlinker/linux64:\
/usr/local/lib \
    fieldagent.Trampoline ${*}

#    -javaagent:$fieldhome/out/artifacts/fieldagent_jar/fieldagent.jar \

# Old f_linux cp entries not in more recent f_mac
#$out/fielded/:\
#$out/fielded/*:\
#$out/fieldbox/:\
#$out/fieldbox/*:\
#$out/fieldnashorn/*:\
#$out/fieldnashorn/:\
#$out/fieldcef_macosx/*:\
